[package]
name = "i3-wsman-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2 = "0.4.3"
i3_ipc = "^0.16.0"
lazy_static = "1.4.0"
serde = "1.0.183"
serde_json = "^1.0.104"
